version: "3.5"
services:
    jenkins:
        container_name: jenkins-docker
        image: jenkins/jenkins:lts
        ports:
            - 8080:8080
        networks:
            - devnetwork
networks:
    devnetwork:
        name: devnetwork
        external: true